# Generated by Django 4.1.2 on 2022-10-21 04:39
# Son generados diferentes archivos por cada modificacion a la estructura de base de datos realizada
# Esto permite llevar un control de versiones sobre la estructura de los datos
# Y asi comparar las diferentes versiones de estructura de la base de datos.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('comments_quantity', models.IntegerField()),
                ('positive_comments', models.IntegerField()),
                ('neutral_comments', models.IntegerField()),
                ('negative_comments', models.IntegerField()),
                ('emotion_comments', models.CharField(max_length=30)),
                ('date_consulted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
