# Generated by Django 4.1.2 on 2022-12-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='comments_quantity',
            new_name='Cantidad_Comentarios',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='app_name',
            new_name='ID_App',
        ),
    ]
